apiVersion: apps/v1
kind: Deployment
metadata:
  name: lite-chat-circle
spec:
  selector:
    matchLabels:
      app: lite-chat-circle
  replicas: 1
  template:
    metadata:
      labels:
        app: lite-chat-circle
    spec:
      containers:
        - name: lite-chat-circle
          image: funtuan/lite-chat-circle:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MONGO_URL
              value: "mongodb://admin:password@mongo:27017"
            - name: FB_WEBHOOK_VERITY_TOKEN
              value: "<FB_WEBHOOK_VERITY_TOKEN>"
            - name: FB_MESSENGER_TOKEN
              value: "<FB_MESSENGER_TOKEN>"
            - name: PORT
              value: "80"
            - name: DAILY_PAIR_LIMIT
              value: "20"